import "./globals.css";
import { Inter } from "next/font/google";
import { SessionContext } from "./session";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionContext session={session}>{children}</SessionContext>
      </body>
    </html>
  );
}
